#!/usr/bin/env python
# -*- coding: utf8 -*-
# Copyright © 2011 Keith Noto.  Disributed under Gnu General Public License (see http://www.gnu.org/licenses/gpl.html).

__author__ = "Keith Noto <noto@cs.tufts.edu>"
__license__ = "GPL"
__copyright__ = "Copyright © 2011 Keith Noto"
VERSION = __revision__ = "1.0"

import sys,string,optparse,os,os.path,copy,fpformat,time,signal,random,math,re

def main():

	import sys,string,optparse,os.path,signal
	signal.signal(signal.SIGPIPE, signal.SIG_DFL) # properly handle SIGPIPE when piping output 

	PROGRAM = os.path.basename(sys.argv[0])
	USAGE = "[options] < input"
	VERSION = "1.0"
	SYNOPSIS = "Convert LIBSVM-format input to FRaC-format input.  Note that the \"target\" (first column) is not part of anomaly-detection tasks and is ignored.  Distributed under Gnu General Public License (see http://www.gnu.org/licenses/gpl.html)."

	parser = optparse.OptionParser(usage="%s %s"%(PROGRAM,USAGE), version="%s version %s"%(PROGRAM,VERSION), description=SYNOPSIS)
	parser.add_option("-d", dest="d", type="int", metavar="Integer", default=None, action="store", help="Number of features (necessary only if first instance does not have the highest-value feature index)")

	(options, args) = parser.parse_args()

	input = open(args[0],'r') if args and args[0]!='-' else sys.stdin
	out = sys.stdout
	d = options.d

	for line in input:
		data = line.split()
		
		V = dict(map(lambda (s,v) : (int(s),v), map(lambda x : tuple(x.split(':',1)), data[1:])))
		m = max(V.keys())
		if d is not None and m > d:
			raise Exception("Found feature serial number %d > number of features %d" % (m,d))
		d = max(d, m) # replace "None"

		out.write("%s\n" % ('\t'.join(map(str, map(lambda i : V[i] if i in V else 0, range(1,d+1))))))

	return

if __name__=='__main__':
	try:
		main()
	except KeyboardInterrupt:
		pass
	except Exception,ex:
		sys.stderr.write("%s: %s\n" % (sys.argv[0], str(ex)))

